export { default as Paragraph } from './Paragraph.vue'
export { default as ParagraphBold } from './ParagraphBold.vue'
export { default as Span } from './Span.vue'
export { default as SpanBold } from './SpanBold.vue'
export { default as Heading } from './Heading.vue'
